"""Package runtime contract helpers for modular distribution."""

from .discovery import (
    DiscoveredPackage,
    PackageDiscoveryFailure,
    discover_package_manifests,
    iter_runtime_package_dirs,
)
from .health import build_package_health_report
from .manifest_loader import (
    PackageContractError,
    PackageManifestError,
    RuntimeOverridesError,
    ToolBindingsError,
    load_package_manifest,
    load_runtime_overrides,
    load_tool_bindings,
)
from .models import (
    ExportKind,
    PackageExport,
    PackageManifest,
    RuntimeOverrideSelection,
    RuntimeOverrides,
    ToolBinding,
    ToolBindingKind,
    ToolBindingsManifest,
)
from .paths import (
    get_file_output_dir,
    get_identifier_prefix_file_path,
    get_identifier_prefix_state_dir,
    get_package_manifest_path,
    get_pdf_storage_dir,
    get_pdfx_json_storage_dir,
    get_processed_json_storage_dir,
    get_runtime_config_dir,
    get_runtime_overrides_path,
    get_runtime_package_dir,
    get_runtime_packages_dir,
    get_runtime_root,
    get_runtime_state_dir,
    get_tool_bindings_path,
)
from .registry import (
    LoadedPackage,
    PackageFailure,
    PackageRegistry,
    PackageRegistryValidationError,
    load_package_registry,
)
from .tool_bindings_loader import (
    LoadedToolBindingExport,
    ToolBindingLoadError,
    load_package_tool_binding_exports,
)
from .tool_registry import (
    RegisteredToolBinding,
    ToolBindingCollision,
    ToolBindingSource,
    ToolRegistry,
    ToolRegistryValidationError,
    build_tool_registry,
    load_tool_registry,
)

__all__ = [
    "DiscoveredPackage",
    "ExportKind",
    "LoadedPackage",
    "PackageContractError",
    "PackageDiscoveryFailure",
    "PackageExport",
    "PackageFailure",
    "PackageManifest",
    "PackageManifestError",
    "PackageRegistry",
    "PackageRegistryValidationError",
    "RegisteredToolBinding",
    "RuntimeOverrideSelection",
    "RuntimeOverrides",
    "RuntimeOverridesError",
    "ToolBinding",
    "ToolBindingCollision",
    "ToolBindingKind",
    "ToolBindingLoadError",
    "ToolBindingSource",
    "ToolBindingsError",
    "ToolBindingsManifest",
    "ToolRegistry",
    "ToolRegistryValidationError",
    "build_package_health_report",
    "build_tool_registry",
    "discover_package_manifests",
    "get_file_output_dir",
    "get_identifier_prefix_file_path",
    "get_identifier_prefix_state_dir",
    "get_package_manifest_path",
    "get_pdf_storage_dir",
    "get_pdfx_json_storage_dir",
    "get_processed_json_storage_dir",
    "get_runtime_config_dir",
    "get_runtime_overrides_path",
    "get_runtime_package_dir",
    "get_runtime_packages_dir",
    "get_runtime_root",
    "get_runtime_state_dir",
    "get_tool_bindings_path",
    "iter_runtime_package_dirs",
    "load_package_tool_binding_exports",
    "load_package_manifest",
    "load_package_registry",
    "load_tool_registry",
    "load_runtime_overrides",
    "load_tool_bindings",
]
