"""File output storage module for generated CSV, TSV, and JSON files.

This module provides storage services for file outputs generated by
file formatter agents. It handles:
- Secure file storage with validation
- Path traversal prevention
- File lifecycle management (create, read, delete)
- Temporary file cleanup

Example usage:
    from src.lib.file_outputs import FileOutputStorageService

    storage = FileOutputStorageService()

    # Save a file output
    path, hash, size, warnings = storage.save_output(
        trace_id="d3b0a19f2c2df7b2b31dfb7cded3acbd",
        session_id="session_abc123",
        content="gene_id,symbol\\nFBgn0001,Notch\\n",
        file_type="csv",
        descriptor="gene_results"
    )

    # Get path for download
    full_path = storage.get_output_path("outputs/2025-01-07/session_abc123/file.csv")
"""

from src.lib.file_outputs.storage import (
    FileOutputStorageError,
    FileOutputStorageService,
    FileSizeError,
    FileValidationError,
    PathSecurityError,
)

__all__ = [
    "FileOutputStorageService",
    "FileOutputStorageError",
    "FileValidationError",
    "PathSecurityError",
    "FileSizeError",
]
