FROM public.ecr.aws/docker/library/node:20-alpine AS builder

WORKDIR /app

ARG VITE_DEV_MODE=true
ARG VITE_GIT_SHA=unknown

COPY package.json package-lock.json* ./

RUN npm ci

COPY index.html .
COPY nginx.conf .
COPY tsconfig.json .
COPY tsconfig.node.json .
COPY vite.config.ts .
COPY public/ ./public/
COPY src/ ./src/

ENV VITE_DEV_MODE=$VITE_DEV_MODE
ENV VITE_GIT_SHA=$VITE_GIT_SHA

RUN export VITE_APP_VERSION=$(node -p "require('./package.json').version") && \
    npm run build


FROM public.ecr.aws/nginx/nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/dist /usr/share/nginx/html
COPY --from=builder /app/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
