# Pre-commit hooks for Alliance AI Curation System
# Install: pip install pre-commit && pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # General code quality hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Prevent large files from being committed
      - id: check-added-large-files
        args: ["--maxkb=1000"]
        exclude: |
          (?x)^(
            backend/tests/fixtures/.*\.pdf$|
            test_paper\.pdf$
          )$

      # Check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict

      # Ensure files end with newline (disabled - not critical)
      # - id: end-of-file-fixer

      # Remove trailing whitespace
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

      # Check JSON syntax
      - id: check-json

      # Check YAML syntax
      - id: check-yaml
        args: ["--unsafe"] # Allow custom YAML tags

      # Check TOML syntax
      - id: check-toml

      # Prevent committing to main/master branches
      - id: no-commit-to-branch
        args: ["--branch", "main", "--branch", "master"]

  # Secrets detection with detect-secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args:
          - "--baseline"
          - ".secrets.baseline"
        exclude: |
          (?x)^(
            .*\.lock$|
            .*package-lock\.json$|
            .*yarn\.lock$|
            node_modules/.*|
            \.git/.*|
            venv/.*|
            __pycache__/.*|
            \.claude/hooks/pydantic_ai_.*_docs\.txt$
          )$

  # GitLeaks for additional secret detection
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
        exclude: |
          (?x)^(
            \.claude/hooks/pydantic_ai_.*_docs\.txt$
          )$

  # Python formatting
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3
        files: \.py$
        exclude: |
          (?x)^(
            venv/.*|
            node_modules/.*
          )$

  # JavaScript/TypeScript formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|json|css|md|yml|yaml)$
        exclude: |
          (?x)^(
            node_modules/.*|
            .*\.lock$|
            package-lock\.json$|
            dist/.*|
            build/.*
          )$

# Configuration for detect-secrets
default_language_version:
  python: python3
