"""PDF extraction task schema.

Individual task specification for PDF extraction workflow.
"""

from typing import List
from pydantic import BaseModel, Field, ConfigDict


class PDFExtractionTask(BaseModel):
    """Single PDF extraction task generated by the planner.

    Note: All fields must be in 'required' array for OpenAI strict mode,
    even those with defaults.
    """

    model_config = ConfigDict(
        extra='forbid',
        json_schema_extra={
            "required": [
                "identifier",
                "objective",
                "instructions",
                "expected_outputs",
                "depends_on",
            ]
        },
    )

    identifier: str = Field(
        description="Short identifier for the extraction task (slug format preferred)"
    )
    objective: str = Field(
        description="Objective for this extraction task (what to retrieve/answer)"
    )
    instructions: str = Field(
        default="",
        description="Additional instructions, hints, or constraints (empty string if none)"
    )
    expected_outputs: List[str] = Field(
        default_factory=list,
        description="List of expected elements to cover in the response"
    )
    depends_on: List[str] = Field(
        default_factory=list,
        description="List of task identifiers that must complete before this task can run (empty list if no dependencies)"
    )
