"""Evidence workspace ownership defects (KANBAN-1775 / ALL-1254).

Three defects found while mapping evidence ownership for KANBAN-1773. They
share that ticket's root cause: evidence records are plain lists of dicts
created independently at three run scopes, with no single insert policy.
"""

import pytest

from src.lib.openai_agents.evidence_summary import _copy_workspace_metadata_fields
from src.lib.openai_agents.tools import evidence_workspace as workspace_module
from src.schemas.evidence_workspace import WORKSPACE_ONLY_FIELDS


@pytest.fixture
def identity_function_tool(monkeypatch):
    """Call the tool implementation directly instead of the SDK wrapper."""
    monkeypatch.setattr(workspace_module, "function_tool", lambda fn: fn)


def _record(**overrides):
    record = {
        "evidence_record_id": "evidence-1",
        "entity": "Adgrl1",
        "verified_quote": "The allele was generated by CRISPR mutagenesis.",
        "page": 3,
        "section": "Results",
        "chunk_id": "chunk-1",
        "status": "verified",
    }
    record.update(overrides)
    return record


class TestDefect1SpecialistInsertPolicy:
    """streaming_tools appended with no dedupe while runner merged by id.

    Re-recording one evidence_record_id inside a specialist run left a second,
    unreachable copy: _find_record returns only the first match, so a later
    attach, detach or metadata update silently addressed the stale copy.
    """

    def test_re_recording_the_same_id_keeps_one_reachable_record(self):
        from src.lib.openai_agents.streaming_tools import _append_live_evidence_record

        live = []
        _append_live_evidence_record(live, _record(verified_quote="First quote."))
        _append_live_evidence_record(live, _record(verified_quote="Second quote."))

        assert len(live) == 1
        assert live[0]["verified_quote"] == "Second quote."

    def test_distinct_ids_are_both_kept_in_order(self):
        from src.lib.openai_agents.streaming_tools import _append_live_evidence_record

        live = []
        _append_live_evidence_record(live, _record(evidence_record_id="evidence-1"))
        _append_live_evidence_record(live, _record(evidence_record_id="evidence-2"))

        assert [r["evidence_record_id"] for r in live] == ["evidence-1", "evidence-2"]

    def test_a_record_without_an_id_is_still_kept(self):
        from src.lib.openai_agents.streaming_tools import _append_live_evidence_record

        live = []
        _append_live_evidence_record(live, _record(evidence_record_id=""))
        _append_live_evidence_record(live, _record(evidence_record_id=""))

        assert len(live) == 2

    def test_the_surviving_record_is_the_one_tools_reach(self):
        from src.lib.openai_agents.streaming_tools import _append_live_evidence_record

        live = []
        _append_live_evidence_record(live, _record(verified_quote="First quote."))
        _append_live_evidence_record(live, _record(verified_quote="Second quote."))

        found = workspace_module._find_record(
            "evidence-1", document_id="doc-1", records=live
        )
        assert found is not None
        assert found["verified_quote"] == "Second quote."


class TestReplacementPreservesTheRicherCopy:
    """Review findings on the defect-1 fix. Replacing by ID is not enough.

    record_evidence mutates the workspace dict in place and keeps the revision
    history there, but strips history from its own tool OUTPUT
    (record_evidence.py:1208 _strip_hidden_revision_history). The stream
    handler builds the replacement from that output, so a naive slot
    replacement swaps the rich copy for the poor one and the audit trail is
    lost. runner.py:691-699 has exactly this guard; the specialist side needs
    it too, and more so, because the specialist dict is the only carrier.
    """

    def test_revision_history_is_carried_forward(self):
        from src.lib.openai_agents.streaming_tools import _append_live_evidence_record

        history = [{"revision": 1, "previous_source": {"verified_quote": "Old quote."}}]
        live = [_record(verified_quote="Old quote.", evidence_revision_history=history)]

        # The summary built from the tool output has no history.
        _append_live_evidence_record(live, _record(verified_quote="Corrected quote."))

        assert live[0]["verified_quote"] == "Corrected quote."
        assert live[0]["evidence_revision_history"] == history

    def test_incoming_history_wins_when_present(self):
        from src.lib.openai_agents.streaming_tools import _append_live_evidence_record

        old = [{"revision": 1, "previous_source": {"verified_quote": "First."}}]
        new = [
            {"revision": 1, "previous_source": {"verified_quote": "First."}},
            {"revision": 2, "previous_source": {"verified_quote": "Second."}},
        ]
        live = [_record(evidence_revision_history=old)]

        _append_live_evidence_record(live, _record(evidence_revision_history=new))

        assert live[0]["evidence_revision_history"] == new

    def test_a_discarded_record_is_not_resurrected(self):
        """The id is a content hash, so re-quoting the same span reuses it.

        record_evidence only runs its "discarded evidence cannot be
        source-updated" guard when the agent supplies an explicit id. Without
        one, a clean ACTIVE record carrying the same derived id would overwrite
        the discard and delete discard_reason with it.
        """
        from src.lib.openai_agents.streaming_tools import _append_live_evidence_record

        live = [_record(
            status="discarded",
            workspace_status="discarded",
            discard_reason="Superseded by a better quote.",
            discarded_at="2026-09-18T12:32:00+00:00",
        )]

        _append_live_evidence_record(live, _record(status="verified"))

        assert live[0]["workspace_status"] == "discarded"
        assert live[0]["discard_reason"] == "Superseded by a better quote."
        assert len(live) == 1, "the discard stands; do not append a rival copy either"

    def test_attachment_metadata_is_not_lost(self):
        from src.lib.openai_agents.streaming_tools import _append_live_evidence_record

        live = [_record(
            object_id="obj-1",
            field_path="attributes.symbol",
            envelope_targets=[{"object_id": "obj-1", "field_path": "attributes.symbol"}],
        )]

        _append_live_evidence_record(live, _record(verified_quote="Corrected quote."))

        assert live[0]["verified_quote"] == "Corrected quote."
        assert live[0]["object_id"] == "obj-1"
        assert live[0]["envelope_targets"][0]["field_path"] == "attributes.symbol"


class TestDefect2LifecycleMustNotEnterCanonicalOutput:
    """Defect 2 has no safe local fix, and this test records why.

    The ownership map flagged that _copy_workspace_metadata_fields omits every
    lifecycle field, so a merge into the runner collection destroys the work of
    attach, detach, discard and metadata updates.

    Widening that whitelist is the obvious fix and it is wrong. The record this
    function builds is canonical output: it flows through
    canonicalize_structured_result_payload into DomainEnvelopeExtractionResult,
    which sets extra='forbid' and rejects exactly those keys. Adding them
    reintroduces the KANBAN-1773 leak from the other side.

    Discard is already honoured by exclusion (evidence_summary.py:217-218 drops
    discarded records), so the practical loss is narrower than it first looked.
    The real fix is a workspace wrapper that holds lifecycle beside an unchanged
    EvidenceRecord, with canonical output projecting it away.
    """

    def test_canonical_output_stays_free_of_lifecycle_state(self):
        evidence_record = {}
        _copy_workspace_metadata_fields(
            evidence_record,
            {
                "object_id": "obj-1",
                "status": "verified",
                "workspace_status": "active",
                "updated_at": "2026-09-18T12:31:54+00:00",
                "discard_reason": "Superseded by a better quote.",
                "discarded_at": "2026-09-18T12:32:00+00:00",
            },
        )

        assert evidence_record["object_id"] == "obj-1"
        for field in WORKSPACE_ONLY_FIELDS:
            assert field not in evidence_record, (
                f"{field} would be rejected by DomainEnvelopeExtractionResult"
            )

    def test_existing_provenance_copying_still_works(self):
        evidence_record = {}
        _copy_workspace_metadata_fields(
            evidence_record, {"object_id": "obj-1", "field_path": "attributes.symbol"}
        )
        assert evidence_record["object_id"] == "obj-1"
        assert evidence_record["field_path"] == "attributes.symbol"


class TestDefect3ExplicitWorkspaceOwnership:
    """discard_recorded_evidence always resolved the ContextVar.

    Validator dispatch runs under asyncio.to_thread, which copies the caller
    context, so inside a validator that ContextVar still pointed at the
    specialist's collection. Every other evidence tool takes workspace_records.
    """

    def test_discard_tool_accepts_an_explicit_workspace(self):
        import inspect

        signature = inspect.signature(
            workspace_module.create_discard_recorded_evidence_tool
        )
        assert "workspace_records" in signature.parameters

    def test_discard_tool_matches_its_siblings(self):
        import inspect

        expected = {"workspace_records", "allowed_evidence_record_ids"}
        for factory_name in (
            "create_attach_evidence_to_object_tool",
            "create_detach_evidence_from_object_tool",
            "create_update_recorded_evidence_metadata_tool",
            "create_discard_recorded_evidence_tool",
        ):
            factory = getattr(workspace_module, factory_name)
            parameters = set(inspect.signature(factory).parameters)
            assert expected <= parameters, f"{factory_name} is missing {expected - parameters}"

    @pytest.mark.asyncio
    async def test_discard_mutates_the_given_workspace_not_the_contextvar(
        self, identity_function_tool
    ):
        contextvar_records = [_record(evidence_record_id="evidence-1")]
        explicit_records = [_record(evidence_record_id="evidence-1")]

        token = workspace_module.set_active_evidence_records(contextvar_records)
        try:
            tool = workspace_module.create_discard_recorded_evidence_tool(
                "doc-1", "user-1", workspace_records=explicit_records
            )
            await tool("evidence-1", "Superseded by a better quote.")
        finally:
            workspace_module.reset_active_evidence_records(token)

        assert explicit_records[0]["workspace_status"] == "discarded"
        assert "workspace_status" not in contextvar_records[0]
