"""SQLAlchemy model for file outputs generated by file formatter agents."""

import enum
from datetime import datetime
from uuid import UUID, uuid4

from sqlalchemy import BigInteger, CheckConstraint, DateTime, Integer, String, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PostgresUUID
from sqlalchemy.orm import Mapped, mapped_column

from src.models.sql.database import Base


class FileType(str, enum.Enum):
    """Supported file output types."""

    CSV = "csv"
    TSV = "tsv"
    JSON = "json"


class FileOutput(Base):
    """File generated by a file output agent (CSV, TSV, JSON formatter).

    Every generated file must be linked to a Langfuse trace for audit purposes.
    """

    __tablename__ = "file_outputs"

    id: Mapped[UUID] = mapped_column(
        PostgresUUID(as_uuid=True),
        primary_key=True,
        default=uuid4,
        server_default=func.gen_random_uuid(),
    )

    # File Identity
    filename: Mapped[str] = mapped_column(String(512), nullable=False)
    file_path: Mapped[str] = mapped_column(String, nullable=False, unique=True)
    file_type: Mapped[str] = mapped_column(String(20), nullable=False)
    file_size: Mapped[int] = mapped_column(BigInteger, nullable=False)
    file_hash: Mapped[str | None] = mapped_column(String(64), nullable=True)

    # User & Session Context (REQUIRED)
    curator_id: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    session_id: Mapped[str] = mapped_column(String(255), nullable=False, index=True)

    # Trace Linkage (MANDATORY for audit)
    trace_id: Mapped[str] = mapped_column(String(32), nullable=False, index=True)

    # Agent & Generation Context
    agent_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    generation_model: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # Flexible Metadata (named file_metadata to avoid SQLAlchemy reserved name)
    file_metadata: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    # Usage Tracking
    download_count: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    last_download_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Lifecycle
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        index=True,
    )

    __table_args__ = (
        CheckConstraint(
            "file_type IN ('csv', 'tsv', 'json')",
            name="ck_file_outputs_file_type",
        ),
        CheckConstraint(
            "file_size > 0",
            name="ck_file_outputs_file_size",
        ),
        CheckConstraint(
            "length(trace_id) = 32",
            name="ck_file_outputs_trace_id",
        ),
        CheckConstraint(
            "curator_id <> ''",
            name="ck_file_outputs_curator_id",
        ),
        CheckConstraint(
            "session_id <> ''",
            name="ck_file_outputs_session_id",
        ),
    )

    def __repr__(self) -> str:
        return f"<FileOutput(id={self.id}, filename='{self.filename}', type='{self.file_type}')>"
