"""Canonical persistence limits shared by flow schemas and Agent Studio."""

FLOW_DEFINITION_MAX_NODES_DEFAULT = 31
FLOW_NAME_MAX_CHARS = 255
FLOW_DESCRIPTION_MAX_CHARS = 2_000
FLOW_STEP_GOAL_MAX_CHARS = 500
FLOW_CUSTOM_INSTRUCTIONS_MAX_CHARS = 2_000
FLOW_OUTPUT_FILENAME_TEMPLATE_MAX_CHARS = 255
