"""All seven packs share one evidence projection but keep their own policy.

KANBAN-1773. The seven `allowed_fields = set(EvidenceRecord.model_fields)` loops
were replaced by `normalize_workspace_records`. Two packs were never identical
to the other five, and flattening them would have changed behavior silently:

- GO drops evidence with no verified quote.
- gene_expression reports each dropped record.

One test file for all seven, rather than seven copies of the same test.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[5]
ALLIANCE_PYTHON_SRC = REPO_ROOT / "packages" / "alliance" / "python" / "src"
if str(ALLIANCE_PYTHON_SRC) not in sys.path:
    sys.path.insert(0, str(ALLIANCE_PYTHON_SRC))

from agr_ai_curation_alliance.domain_packs.allele.conversion import (  # noqa: E402
    _normalized_evidence_records as allele_normalize,
)
from agr_ai_curation_alliance.domain_packs.disease.builder_conversion import (  # noqa: E402
    _normalized_evidence_records as disease_normalize,
)
from agr_ai_curation_alliance.domain_packs.gene.conversion import (  # noqa: E402
    _gene_normalized_evidence_records as gene_normalize,
)
from agr_ai_curation_alliance.domain_packs.gene_expression.conversion import (  # noqa: E402
    _normalized_evidence_records as gene_expression_normalize,
)
from agr_ai_curation_alliance.domain_packs.generic.conversion import (  # noqa: E402
    _normalized_evidence_records as generic_normalize,
)
from agr_ai_curation_alliance.domain_packs.go.conversion import (  # noqa: E402
    _normalized_evidence_records as go_normalize,
)
from agr_ai_curation_alliance.domain_packs.phenotype.conversion import (  # noqa: E402
    _normalized_evidence_records as phenotype_normalize,
)

ALL_PACKS = [
    pytest.param(generic_normalize, id="generic"),
    pytest.param(allele_normalize, id="allele"),
    pytest.param(gene_normalize, id="gene"),
    pytest.param(gene_expression_normalize, id="gene_expression"),
    pytest.param(go_normalize, id="go"),
    pytest.param(phenotype_normalize, id="phenotype"),
    pytest.param(disease_normalize, id="disease"),
]

BASELINE_PACKS = [
    pytest.param(generic_normalize, id="generic"),
    pytest.param(allele_normalize, id="allele"),
    pytest.param(gene_normalize, id="gene"),
    pytest.param(phenotype_normalize, id="phenotype"),
    pytest.param(disease_normalize, id="disease"),
    pytest.param(gene_expression_normalize, id="gene_expression"),
]


def _workspace_record(**overrides):
    record = {
        "status": "verified",
        "entity": "Adgrl1",
        "span_ids": ["span-1"],
        "source_span_ids": ["span-1"],
        "verified_quote": "The allele was generated by CRISPR mutagenesis.",
        "page": 3,
        "section": "Results",
        "chunk_id": "chunk-1",
        "document_id": "doc-1",
        "evidence_record_id": "evidence-1",
        "updated_at": "2026-09-18T12:31:54+00:00",
    }
    record.update(overrides)
    return record


@pytest.mark.parametrize("normalize", ALL_PACKS)
class TestEveryPackSharesTheProjection:
    def test_workspace_fields_never_reach_canonical_evidence(self, normalize):
        record, = normalize([_workspace_record()])
        for field in ("status", "workspace_status", "span_ids", "updated_at",
                      "created_at", "discarded_at", "discard_reason"):
            assert field not in record

    def test_provenance_survives(self, normalize):
        record, = normalize([_workspace_record()])
        assert record["source_span_ids"] == ["span-1"]
        assert record["verified_quote"] == "The allele was generated by CRISPR mutagenesis."
        assert record["chunk_id"] == "chunk-1"
        assert record["document_id"] == "doc-1"

    def test_discarded_records_are_excluded(self, normalize):
        records = [_workspace_record(workspace_status="discarded", status="discarded")]
        assert normalize(records) == []

    def test_duplicate_ids_keep_the_first(self, normalize):
        records = [_workspace_record(entity="first"), _workspace_record(entity="second")]
        result = normalize(records)
        assert len(result) == 1
        assert result[0]["entity"] == "first"

    def test_records_without_an_id_are_excluded(self, normalize):
        assert normalize([_workspace_record(evidence_record_id="")]) == []

    def test_non_mappings_are_skipped(self, normalize):
        assert len(normalize(["nonsense", None, _workspace_record()])) == 1

    def test_span_alias_alone_is_adopted(self, normalize):
        record = _workspace_record()
        del record["source_span_ids"]
        projected, = normalize([record])
        assert projected["source_span_ids"] == ["span-1"]


class TestPackSpecificPolicySurvives:
    def test_go_still_requires_a_verified_quote(self):
        """go/conversion.py dropped quote-less evidence before this refactor."""
        records = [_workspace_record(verified_quote=None)]
        assert go_normalize(records) == []

    @pytest.mark.parametrize("normalize", BASELINE_PACKS)
    def test_other_packs_still_admit_quote_less_evidence(self, normalize):
        records = [_workspace_record(verified_quote=None)]
        assert len(normalize(records)) == 1

    def test_gene_expression_still_reports_a_dropped_record(self, caplog):
        """gene_expression/conversion.py logged before dropping."""
        import logging

        with caplog.at_level(logging.WARNING):
            result = gene_expression_normalize([_workspace_record(page="not an integer")])

        assert result == []
        assert any(
            "Dropped malformed gene expression evidence record" in message
            for message in caplog.messages
        )

    @pytest.mark.parametrize("normalize", [
        pytest.param(generic_normalize, id="generic"),
        pytest.param(allele_normalize, id="allele"),
        pytest.param(go_normalize, id="go"),
    ])
    def test_other_packs_drop_quietly(self, normalize, caplog):
        import logging

        with caplog.at_level(logging.WARNING):
            assert normalize([_workspace_record(page="not an integer")]) == []

        assert not any(
            "Dropped malformed gene expression evidence record" in message
            for message in caplog.messages
        )
