"""Contract for the shared evidence workspace/provenance boundary (KANBAN-1773).

One projection converts an internal workspace record into canonical provenance.
Admission policy stays with each caller; this module owns only the projection
and the serialization policy.
"""

import pytest
from pydantic import ValidationError

from src.schemas.models.base import EvidenceRecord
from src.schemas.models.evidence_workspace import (
    WORKSPACE_ONLY_FIELDS,
    EvidenceIntegrityError,
    canonical_evidence_payload,
    is_discarded,
    project_to_provenance,
    try_project_to_provenance,
)


def _workspace_record(**overrides):
    """A record in the shape record_evidence actually writes."""
    record = {
        "status": "verified",
        "entity": "Adgrl1",
        "span_ids": ["span-1", "span-2"],
        "source_span_ids": ["span-1", "span-2"],
        "verified_quote": "The allele was generated by CRISPR mutagenesis.",
        "page": 3,
        "section": "Results",
        "chunk_id": "chunk-1",
        "document_id": "doc-1",
        "evidence_record_id": "evidence-24d4a4973cd8d45f",
        "updated_at": "2026-09-18T12:31:54+00:00",
        "created_at": "2026-09-18T12:20:00+00:00",
    }
    record.update(overrides)
    return record


class TestWorkspaceOnlyFields:
    def test_inventory_matches_what_the_tools_write(self):
        assert WORKSPACE_ONLY_FIELDS == frozenset({
            "status",
            "workspace_status",
            "span_ids",
            "created_at",
            "updated_at",
            "discarded_at",
            "discard_reason",
        })

    def test_no_workspace_field_collides_with_canonical_provenance(self):
        assert not (WORKSPACE_ONLY_FIELDS & set(EvidenceRecord.model_fields))


class TestProjection:
    def test_drops_every_workspace_field(self):
        record = project_to_provenance(_workspace_record())
        dumped = record.model_dump(exclude_none=True)
        for field in WORKSPACE_ONLY_FIELDS:
            assert field not in dumped

    def test_preserves_provenance(self):
        record = project_to_provenance(_workspace_record())
        assert record.evidence_record_id == "evidence-24d4a4973cd8d45f"
        assert record.source_span_ids == ["span-1", "span-2"]
        assert record.verified_quote == "The allele was generated by CRISPR mutagenesis."
        assert record.chunk_id == "chunk-1"
        assert record.document_id == "doc-1"
        assert record.page == 3
        assert record.section == "Results"

    def test_returns_a_validated_model_not_a_dict(self):
        assert isinstance(project_to_provenance(_workspace_record()), EvidenceRecord)

    def test_span_alias_is_adopted_when_canonical_list_is_absent(self):
        record = _workspace_record()
        del record["source_span_ids"]
        assert project_to_provenance(record).source_span_ids == ["span-1", "span-2"]

    def test_canonical_list_wins_over_the_alias(self):
        record = _workspace_record(source_span_ids=["span-9"], span_ids=["span-1"])
        assert project_to_provenance(record).source_span_ids == ["span-9"]

    def test_revision_history_survives(self):
        history = [{"revision": 1, "previous_source": {"verified_quote": "Old.", "chunk_id": "chunk-0"}}]
        record = project_to_provenance(_workspace_record(evidence_revision_history=history))
        assert record.evidence_revision_history == history

    def test_none_values_are_not_emitted(self):
        record = project_to_provenance(_workspace_record(subsection=None))
        assert "subsection" not in record.model_dump(exclude_none=True)

    def test_unknown_field_is_an_integrity_error_not_a_silent_drop(self):
        with pytest.raises(EvidenceIntegrityError) as exc:
            project_to_provenance(_workspace_record(mystery_field="surprise"))
        assert "mystery_field" in str(exc.value)

    def test_integrity_error_is_not_a_pydantic_validation_error(self):
        # Callers branch on this type; it must not be swallowed by ValidationError handlers.
        assert not issubclass(EvidenceIntegrityError, ValidationError)

    def test_rejects_a_non_mapping(self):
        with pytest.raises(EvidenceIntegrityError):
            project_to_provenance(["not", "a", "mapping"])


class TestTryProjection:
    def test_returns_none_instead_of_raising(self):
        assert try_project_to_provenance(_workspace_record(mystery_field="surprise")) is None

    def test_returns_the_record_when_valid(self):
        assert try_project_to_provenance(_workspace_record()).entity == "Adgrl1"


class TestCanonicalPayload:
    def test_emits_json_safe_dict_without_none(self):
        payload = canonical_evidence_payload(_workspace_record())
        assert payload["evidence_record_id"] == "evidence-24d4a4973cd8d45f"
        assert "subsection" not in payload
        assert "span_ids" not in payload
        assert "status" not in payload

    def test_payload_round_trips_through_the_strict_model(self):
        payload = canonical_evidence_payload(_workspace_record())
        assert EvidenceRecord.model_validate(payload).source_span_ids == ["span-1", "span-2"]


class TestLifecycle:
    def test_reads_workspace_status_first(self):
        assert is_discarded({"workspace_status": "discarded", "status": "verified"}) is True

    def test_falls_back_to_status(self):
        assert is_discarded({"status": "discarded"}) is True

    def test_active_record_is_not_discarded(self):
        assert is_discarded(_workspace_record()) is False

    def test_tolerates_surrounding_whitespace(self):
        assert is_discarded({"status": "  discarded  "}) is True


class TestNormalizeWorkspaceRecords:
    """The shared replacement for the seven duplicated pack whitelists.

    Each pack keeps its own admission policy; this helper owns selection order,
    projection, de-duplication and serialization.
    """

    def _records(self):
        return [
            _workspace_record(),
            _workspace_record(evidence_record_id="evidence-2", entity="Wnt1"),
        ]

    def test_projects_and_serializes_each_record(self):
        from src.schemas.models.evidence_workspace import normalize_workspace_records

        out = normalize_workspace_records(self._records())
        assert [r["evidence_record_id"] for r in out] == ["evidence-24d4a4973cd8d45f", "evidence-2"]
        assert all("span_ids" not in r and "status" not in r for r in out)

    def test_skips_non_mappings(self):
        from src.schemas.models.evidence_workspace import normalize_workspace_records

        assert normalize_workspace_records(["nonsense", None, _workspace_record()]) != []
        assert len(normalize_workspace_records(["nonsense", None, _workspace_record()])) == 1

    def test_skips_discarded_before_projecting(self):
        from src.schemas.models.evidence_workspace import normalize_workspace_records

        records = [_workspace_record(workspace_status="discarded", status="discarded")]
        assert normalize_workspace_records(records) == []

    def test_requires_an_evidence_record_id(self):
        from src.schemas.models.evidence_workspace import normalize_workspace_records

        records = [_workspace_record(evidence_record_id="  ")]
        assert normalize_workspace_records(records) == []

    def test_keeps_first_of_a_duplicate_id(self):
        from src.schemas.models.evidence_workspace import normalize_workspace_records

        records = [_workspace_record(entity="first"), _workspace_record(entity="second")]
        out = normalize_workspace_records(records)
        assert len(out) == 1
        assert out[0]["entity"] == "first"

    def test_admission_predicate_can_reject_a_valid_record(self):
        """GO drops evidence with no verified quote (go/conversion.py:610)."""
        from src.schemas.models.evidence_workspace import normalize_workspace_records

        records = [_workspace_record(verified_quote=None)]
        assert normalize_workspace_records(records) != []
        assert normalize_workspace_records(records, admit=lambda r: bool(r.verified_quote)) == []

    def test_rejected_record_does_not_consume_its_id(self):
        """Matches the packs: seen.add happens only after validation and admission."""
        from src.schemas.models.evidence_workspace import normalize_workspace_records

        records = [
            _workspace_record(verified_quote=None),
            _workspace_record(verified_quote="A real quote."),
        ]
        out = normalize_workspace_records(records, admit=lambda r: bool(r.verified_quote))
        assert len(out) == 1
        assert out[0]["verified_quote"] == "A real quote."

    def test_on_drop_is_notified_for_a_malformed_record(self):
        """gene_expression logs before dropping (gene_expression/conversion.py:913)."""
        from src.schemas.models.evidence_workspace import normalize_workspace_records

        dropped = []
        records = [_workspace_record(page="not an integer")]
        out = normalize_workspace_records(records, on_drop=lambda rid, exc: dropped.append(rid))
        assert out == []
        assert dropped == ["evidence-24d4a4973cd8d45f"]

    def test_unknown_field_is_stripped_not_dropped_by_default(self):
        """Preserves current pack behavior: the whitelist ignored unknown keys."""
        from src.schemas.models.evidence_workspace import normalize_workspace_records

        out = normalize_workspace_records([_workspace_record(mystery_field="surprise")])
        assert len(out) == 1
        assert "mystery_field" not in out[0]

    def test_strict_mode_surfaces_an_unknown_field(self):
        from src.schemas.models.evidence_workspace import normalize_workspace_records

        with pytest.raises(EvidenceIntegrityError):
            normalize_workspace_records([_workspace_record(mystery_field="surprise")], strict=True)
