#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
COMPOSE_FILE="${REPO_ROOT}/docker-compose.test.yml"
TEST_STACK_ENV_FILE="${REPO_ROOT}/.test-stack.env"

# Load optional local secrets and runtime vars from home env files.
# This exports values into the current process only.
# shellcheck disable=SC1091
. "${SCRIPT_DIR}/load-home-test-env.sh"

preferred_port_if_available() {
  local env_name="$1"
  local preferred_port="$2"

  if [[ -n "${!env_name:-}" ]]; then
    export "${env_name}=${!env_name}"
    return 0
  fi

  if python3 - "${preferred_port}" <<'PY'
import socket
import sys

port = int(sys.argv[1])
sock = socket.socket()
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
try:
    sock.bind(("127.0.0.1", port))
except OSError:
    sys.exit(1)
finally:
    sock.close()
sys.exit(0)
PY
  then
    export "${env_name}=${preferred_port}"
  fi
}

resolve_published_port() {
  local service_name="$1"
  local container_port="$2"
  local published

  published="$(docker compose -f "${COMPOSE_FILE}" port "${service_name}" "${container_port}" | head -n 1)"
  if [[ -z "${published}" ]]; then
    echo "Unable to resolve published port for ${service_name}:${container_port}" >&2
    exit 1
  fi

  printf '%s\n' "${published##*:}"
}

write_test_stack_env() {
  cat > "${TEST_STACK_ENV_FILE}" <<EOF
# Generated by scripts/testing/prepare-test-stack.sh
# Safe to delete; regenerated on next prepare.
export TEST_DB_PORT_HOST=${TEST_DB_PORT_HOST}
export TEST_DB_PORT=${TEST_DB_PORT_HOST}
export TEST_DB_HOST=127.0.0.1
export TEST_WEAVIATE_PORT_HOST=${TEST_WEAVIATE_PORT_HOST}
export WEAVIATE_HOST=127.0.0.1
export WEAVIATE_PORT=${TEST_WEAVIATE_PORT_HOST}
export TEST_WEAVIATE_GRPC_PORT_HOST=${TEST_WEAVIATE_GRPC_PORT_HOST}
export WEAVIATE_GRPC_HOST=127.0.0.1
export WEAVIATE_GRPC_PORT=${TEST_WEAVIATE_GRPC_PORT_HOST}
EOF
}

# Defaults for isolated test infrastructure.
export TEST_DB_USER="${TEST_DB_USER:-postgres}"
export TEST_DB_PASSWORD="${TEST_DB_PASSWORD:-postgres}"
export TEST_DB_NAME="${TEST_DB_NAME:-ai_curation}"
export TEST_REDIS_PASSWORD="${TEST_REDIS_PASSWORD:-CHANGE_ME_TEST_REDIS_PASSWORD}"

export TEST_DB_HOST="${TEST_DB_HOST:-postgres-test}"
export TEST_DB_PORT="${TEST_DB_PORT:-5432}"

preferred_port_if_available TEST_DB_PORT_HOST 15434
preferred_port_if_available TEST_WEAVIATE_PORT_HOST 18080
preferred_port_if_available TEST_WEAVIATE_GRPC_PORT_HOST 15051

TEST_DATABASE_URL_IN_STACK="postgresql://${TEST_DB_USER}:${TEST_DB_PASSWORD}@${TEST_DB_HOST}:${TEST_DB_PORT}/${TEST_DB_NAME}"

echo "Starting isolated test infrastructure (postgres-test + weaviate-test)..."
# Ensure deterministic infra state for schema-sensitive integration tests.
# Recreate test containers so stale Weaviate schemas (for example legacy
# non-vectorized DocumentChunk classes) do not persist across runs.
docker compose -f "${COMPOSE_FILE}" rm -sf \
  postgres-test \
  reranker-transformers-test \
  redis-test \
  weaviate-test >/dev/null 2>&1 || true

docker compose -f "${COMPOSE_FILE}" up -d --wait \
  postgres-test \
  reranker-transformers-test \
  redis-test \
  weaviate-test

TEST_DB_PORT_HOST="$(resolve_published_port postgres-test 5432)"
TEST_WEAVIATE_PORT_HOST="$(resolve_published_port weaviate-test 8080)"
TEST_WEAVIATE_GRPC_PORT_HOST="$(resolve_published_port weaviate-test 50051)"
TEST_DATABASE_URL_HOST="postgresql://${TEST_DB_USER}:${TEST_DB_PASSWORD}@127.0.0.1:${TEST_DB_PORT_HOST}/${TEST_DB_NAME}"
write_test_stack_env

if [[ "${SKIP_TEST_DB_MIGRATIONS:-0}" == "1" ]]; then
  echo "Skipping Alembic migrations because SKIP_TEST_DB_MIGRATIONS=1."
else
  echo "Applying Alembic migrations to test database..."
  docker compose -f "${COMPOSE_FILE}" run --rm \
    -e DATABASE_URL="${TEST_DATABASE_URL_IN_STACK}" \
    backend-unit-tests \
    bash -lc "cd /app/backend && alembic upgrade head"
fi

echo "Test infrastructure is ready."
echo "Postgres host port: ${TEST_DB_PORT_HOST}"
echo "Weaviate host port: ${TEST_WEAVIATE_PORT_HOST}"
echo "Weaviate gRPC host port: ${TEST_WEAVIATE_GRPC_PORT_HOST}"
echo "Host DATABASE_URL example: ${TEST_DATABASE_URL_HOST}"
echo "Resolved test stack env file: ${TEST_STACK_ENV_FILE}"
