"""
Agent Definition Loader for Config-Driven Architecture.

This module discovers and loads agent definitions from installed runtime
packages plus the repo/runtime override layer under `config/agents/`. Each
resolved agent bundle contains:
- agent.yaml: Agent metadata and configuration
- prompt.yaml: Base prompt template
- schema.py: Pydantic output schema (optional)
- group_rules/: Organization-specific rules (optional)

Usage:
    from src.lib.config import load_agent_definitions, get_agent_definition

    # Load all agents from packages plus config overrides at startup
    agents = load_agent_definitions()

    # Get a specific agent
    gene_agent = get_agent_definition("gene_validation")
"""

import logging
import os
import threading
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Dict, List, Optional, Any

import yaml

from .agent_sources import resolve_agent_config_sources

logger = logging.getLogger(__name__)

# Thread safety lock for initialization
_init_lock = threading.Lock()


@dataclass
class SupervisorRouting:
    """Configuration for how the supervisor routes to this agent.

    Note: The supervisor tool name (e.g., ask_gene_specialist) is NOT stored here.
    It is generated by AgentDefinition.tool_name based on the canonical system-agent key.
    """

    enabled: bool = True
    description: str = ""
    batchable: bool = False
    batching_instructions: str = ""
    batching_entity: str = ""  # e.g., "genes", "alleles" - for batching nudge prompts


def _expand_env_ref(value: Any) -> str:
    """Expand an agent.yaml config value that may reference the environment.

    Supported forms:
      - "literal"            -> returned unchanged
      - "${VAR}"             -> required; raises if VAR is unset (no fallback)
      - "${VAR:-default}"    -> VAR if set, else the package-declared default

    The package agent.yaml is the only place a model literal default may live;
    code never substitutes one.
    """
    text = str(value).strip()
    if not (text.startswith("${") and text.endswith("}")):
        return text

    inner = text[2:-1]
    if ":-" in inner:
        var_name, default_val = inner.split(":-", 1)
        return os.environ.get(var_name.strip(), default_val)

    var_name = inner.strip()
    resolved = os.environ.get(var_name)
    if resolved is None or not resolved.strip():
        raise ValueError(
            f"Environment variable '{var_name}' referenced in agent.yaml is not "
            f"set, and there is no code fallback. Define it in .env."
        )
    return resolved


@dataclass
class ModelConfig:
    """LLM configuration for the agent.

    ``model`` is required and is supplied by the package ``agent.yaml`` (the
    per-package config contract); a yaml that omits it fails fast rather than
    silently running on a code-default model. ``reasoning`` and ``temperature``
    are optional and declared in the yaml only when used: an agent that omits
    ``reasoning`` (e.g. the supervisor) resolves it from AGENT_*_REASONING or the
    required DEFAULT_AGENT_REASONING in .env, and ``temperature`` only matters for
    models that use it (e.g. Gemini). There are no code-side model literals.
    """

    model: str
    reasoning: Optional[str] = None
    temperature: Optional[float] = None


@dataclass
class FrontendConfig:
    """Frontend display configuration."""

    icon: str = "🤖"
    show_in_palette: bool = True


@dataclass
class CurationConfig:
    """Optional curation-routing metadata declared by the owning package."""

    adapter_key: str | None = None
    domain_pack_id: str | None = None
    launchable: bool = False


@dataclass
class AgentDefinition:
    """
    Complete agent definition loaded from agent.yaml.

    Attributes:
        folder_name: The folder name (e.g., "gene", "allele")
        agent_id: Unique identifier (e.g., "gene_validation")
        system_agent_key: Optional public key for the unified system-agent row
        name: Human-readable name
        description: Brief description of agent capabilities
        category: Agent category (e.g., "Validation", "Extraction")
        subcategory: Agent subcategory
        supervisor_routing: Routing configuration for supervisor
        tools: List of tool names this agent can use
        output_schema: Name of Pydantic schema class (or None)
        model_config: LLM settings
        requires_document: Whether agent needs a loaded document
        required_params: List of required parameter names
        batch_capabilities: List of batch operation types supported
        group_rules_enabled: Whether to inject group-specific rules
        frontend: Frontend display settings
        tool_name: Generated supervisor tool name (ask_{canonical_system_agent_key}_specialist)
    """

    folder_name: str
    agent_id: str
    name: str
    package_id: Optional[str] = None
    package_path: Optional[Path] = None
    system_agent_key: Optional[str] = None
    description: str = ""
    category: str = ""
    subcategory: str = ""
    supervisor_routing: SupervisorRouting = field(default_factory=SupervisorRouting)
    tools: List[str] = field(default_factory=list)
    output_schema: Optional[str] = None
    model_config: Optional[ModelConfig] = None
    requires_document: bool = False
    required_params: List[str] = field(default_factory=list)
    batch_capabilities: List[str] = field(default_factory=list)
    group_rules_enabled: bool = False
    frontend: FrontendConfig = field(default_factory=FrontendConfig)
    curation: CurationConfig = field(default_factory=CurationConfig)
    documentation: Optional[Dict[str, Any]] = None
    # model_config is required for agents that are actually executed; that is
    # enforced at the real use-point (from_yaml requires a model; building the
    # agent registry / config raises on a missing model_config). It stays optional
    # on the dataclass so non-execution helpers can construct lightweight agents.

    @property
    def tool_name(self) -> str:
        """Generate the supervisor tool name from the canonical system-agent key."""
        return f"ask_{canonical_system_agent_key(self).replace('-', '_')}_specialist"

    @classmethod
    def from_yaml(
        cls,
        folder_name: str,
        data: Dict[str, Any],
        *,
        package_id: Optional[str] = None,
        package_path: Optional[Path] = None,
    ) -> "AgentDefinition":
        """
        Create an AgentDefinition from parsed YAML data.

        Args:
            folder_name: Name of the agent folder
            data: Parsed YAML dictionary

        Returns:
            AgentDefinition instance
        """
        # Parse supervisor_routing
        routing_data = data.get("supervisor_routing", {})
        is_batchable = routing_data.get("batchable", False)
        # Default entity to folder_name + "s" (simple pluralization) if batchable
        default_entity = f"{folder_name}s" if is_batchable else ""
        supervisor_routing = SupervisorRouting(
            enabled=routing_data.get("enabled", True),
            description=routing_data.get("description", "").strip(),
            batchable=is_batchable,
            batching_instructions=routing_data.get("batching_instructions", "").strip(),
            batching_entity=routing_data.get("batching_entity", default_entity).strip(),
        )

        # Parse model_config from the package agent.yaml (the config contract).
        # When model_config is present, model is REQUIRED (no code-side fallback);
        # reasoning/temperature stay optional (e.g. the supervisor omits reasoning).
        # The yaml's own ${VAR:-default} is the package default, expanded against the
        # environment by _expand_env_ref. When model_config is absent entirely the
        # definition still loads with no model, and the fail-fast is deferred to the
        # point of use: building the agent registry (and runtime model resolution)
        # raises on a missing model. That lets lightweight agents that are only
        # loaded for inspection (never executed) load without forcing a model here.
        model_data = data.get("model_config")
        if not model_data:
            model_config = None
        else:
            if "model" not in model_data:
                raise ValueError(
                    f"Agent '{folder_name}' agent.yaml model_config is missing required 'model'."
                )

            temperature_raw = model_data.get("temperature")
            temperature = (
                float(_expand_env_ref(temperature_raw))
                if temperature_raw is not None and str(temperature_raw).strip() != ""
                else None
            )
            reasoning_raw = model_data.get("reasoning")
            reasoning = (
                _expand_env_ref(reasoning_raw)
                if reasoning_raw is not None and str(reasoning_raw).strip() != ""
                else None
            )
            model_config = ModelConfig(
                model=_expand_env_ref(model_data["model"]),
                reasoning=reasoning,
                temperature=temperature,
            )

        # Parse frontend config
        frontend_data = data.get("frontend", {})
        frontend = FrontendConfig(
            icon=frontend_data.get("icon", "🤖"),
            show_in_palette=frontend_data.get("show_in_palette", True),
        )
        curation_data = data.get("curation", {})
        curation = CurationConfig(
            adapter_key=str(curation_data.get("adapter_key") or "").strip() or None,
            domain_pack_id=str(curation_data.get("domain_pack_id") or "").strip() or None,
            launchable=bool(curation_data.get("launchable", False)),
        )

        return cls(
            folder_name=folder_name,
            agent_id=data.get("agent_id", folder_name),
            name=data.get("name", folder_name.replace("_", " ").title()),
            package_id=package_id,
            package_path=package_path,
            system_agent_key=str(data.get("system_agent_key") or "").strip() or None,
            description=data.get("description", "").strip(),
            category=data.get("category", ""),
            subcategory=data.get("subcategory", ""),
            supervisor_routing=supervisor_routing,
            tools=data.get("tools", []),
            output_schema=data.get("output_schema"),
            model_config=model_config,
            requires_document=data.get("requires_document", False),
            required_params=data.get("required_params", []),
            batch_capabilities=data.get("batch_capabilities", []),
            group_rules_enabled=data.get("group_rules_enabled", False),
            frontend=frontend,
            curation=curation,
            documentation=data.get("documentation"),
        )


def canonical_system_agent_key(agent: AgentDefinition) -> str:
    """Return the unified-agents key for a shipped/package-owned system agent."""
    if agent.system_agent_key:
        return agent.system_agent_key
    if agent.folder_name == "pdf":
        return agent.agent_id
    return agent.folder_name


# Module-level cache for loaded agents
_agent_registry: Dict[str, AgentDefinition] = {}
_agents_by_folder: Dict[str, AgentDefinition] = {}
_agents_by_package_and_id: Dict[tuple[str, str], AgentDefinition] = {}
_initialized: bool = False


def _load_agent_definition_indexes(
    agents_path: Optional[Path] = None,
) -> tuple[
    Dict[str, AgentDefinition],
    Dict[str, AgentDefinition],
    Dict[tuple[str, str], AgentDefinition],
]:
    """Load agent definition indexes from sources without mutating module cache."""

    agent_registry: Dict[str, AgentDefinition] = {}
    agents_by_folder: Dict[str, AgentDefinition] = {}
    agents_by_package_and_id: Dict[tuple[str, str], AgentDefinition] = {}

    for source in resolve_agent_config_sources(agents_path):
        agent_yaml = source.agent_yaml
        if source.package_id and (agent_yaml is None or not agent_yaml.exists()):
            raise FileNotFoundError(
                f"Package '{source.package_id}' agent bundle '{source.folder_name}' "
                f"is missing agent.yaml at {agent_yaml}"
            )

        if agent_yaml is None or not agent_yaml.exists():
            logger.debug('Skipping %s: no agent.yaml found', source.folder_name)
            continue

        try:
            with open(agent_yaml, "r", encoding="utf-8") as f:
                data = yaml.safe_load(f)

            if not data:
                logger.warning('Empty agent.yaml in %s', source.folder_name)
                continue

            docs_yaml_path = source.docs_yaml
            docs_data = None
            if docs_yaml_path is not None and docs_yaml_path.exists():
                if data.get("documentation"):
                    raise ValueError(
                        f"Agent '{source.folder_name}' declares both an inline "
                        f"'documentation' block in agent.yaml and a docs.yaml; "
                        f"keep curator docs only in docs.yaml."
                    )
                with open(docs_yaml_path, "r", encoding="utf-8") as docs_file:
                    docs_data = yaml.safe_load(docs_file)
                if not docs_data:
                    logger.warning('Empty docs.yaml in %s', source.folder_name)

            agent = AgentDefinition.from_yaml(
                source.folder_name,
                data,
                package_id=source.package_id,
                package_path=source.package_path,
            )
            if docs_data is not None:
                agent.documentation = docs_data
            agent_registry[agent.agent_id] = agent
            agents_by_folder[source.folder_name] = agent
            if agent.package_id is not None:
                agents_by_package_and_id[(agent.package_id, agent.agent_id)] = agent

            logger.info(
                f"Loaded agent: {agent.agent_id} "
                f"(folder={source.folder_name}, tool={agent.tool_name})"
            )

        except yaml.YAMLError as e:
            logger.error('Failed to parse %s: %s', agent_yaml, e)
            raise
        except Exception as e:
            logger.error(
                'Failed to load agent from %s%s: %s',
                source.folder_name,
                f" in package {source.package_id}" if source.package_id else "",
                e,
            )
            raise

    return agent_registry, agents_by_folder, agents_by_package_and_id


def build_package_scoped_agent_resolver(
    agents_path: Optional[Path] = None,
) -> Callable[[str, str], Optional[AgentDefinition]]:
    """Build a package-scoped agent resolver without changing the shared cache."""

    agents_by_package_and_id: Dict[tuple[str, str], AgentDefinition] | None = None
    resolver_lock = threading.Lock()

    def resolve(package_id: str, agent_id: str) -> Optional[AgentDefinition]:
        nonlocal agents_by_package_and_id
        if agents_by_package_and_id is None:
            with resolver_lock:
                if agents_by_package_and_id is None:
                    (
                        _registry,
                        _folders,
                        agents_by_package_and_id,
                    ) = _load_agent_definition_indexes(agents_path)
        return agents_by_package_and_id.get((package_id, agent_id))

    return resolve


def load_agent_definitions(
    agents_path: Optional[Path] = None,
    force_reload: bool = False,
) -> Dict[str, AgentDefinition]:
    """
    Discover and load all agent definitions from YAML files.

    Scans the agents directory for folders containing agent.yaml files.
    Folders starting with underscore (_) are skipped (e.g., _examples/).

    This function is thread-safe; concurrent calls will block until
    initialization is complete.

    Args:
        agents_path: Optional search path. When omitted, scan runtime packages
            plus `config/agents/` overrides when present.
        force_reload: Force reload even if already initialized

    Returns:
        Dictionary mapping agent_id to AgentDefinition

    Raises:
        FileNotFoundError: If agents_path doesn't exist
        yaml.YAMLError: If YAML parsing fails
    """
    global _agent_registry, _agents_by_folder, _agents_by_package_and_id, _initialized

    # Thread-safe initialization
    with _init_lock:
        if _initialized and not force_reload:
            return _agent_registry

        logger.info(
            'Loading agent definitions from: %s',
            agents_path or "default runtime package search path",
        )

        (
            _agent_registry,
            _agents_by_folder,
            _agents_by_package_and_id,
        ) = _load_agent_definition_indexes(agents_path)

        _initialized = True
        logger.info('Loaded %s agent definitions', len(_agent_registry))

        return _agent_registry


def get_agent_definition(agent_id: str) -> Optional[AgentDefinition]:
    """
    Get an agent definition by its agent_id.

    Args:
        agent_id: The agent identifier (e.g., "gene_validation")

    Returns:
        AgentDefinition or None if not found
    """
    if not _initialized:
        load_agent_definitions()

    return _agent_registry.get(agent_id)


def get_agent_by_folder(folder_name: str) -> Optional[AgentDefinition]:
    """
    Get an agent definition by its folder name.

    Args:
        folder_name: The folder name (e.g., "gene")

    Returns:
        AgentDefinition or None if not found
    """
    if not _initialized:
        load_agent_definitions()

    return _agents_by_folder.get(folder_name)


def get_agent_definition_for_package(
    package_id: str,
    agent_id: str,
) -> Optional[AgentDefinition]:
    """Get an agent definition by package owner and agent ID."""
    if not _initialized:
        load_agent_definitions()

    return _agents_by_package_and_id.get((package_id, agent_id))


def get_agent_by_tool_name(tool_name: str) -> Optional[AgentDefinition]:
    """
    Get an agent definition by its supervisor tool name.

    Args:
        tool_name: The tool name (e.g., "ask_gene_specialist")

    Returns:
        AgentDefinition or None if not found
    """
    if not _initialized:
        load_agent_definitions()

    for agent in _agent_registry.values():
        if agent.tool_name == tool_name:
            return agent

    return None


def list_agents(
    enabled_only: bool = False,
    category: Optional[str] = None,
) -> List[AgentDefinition]:
    """
    List all loaded agent definitions.

    Args:
        enabled_only: Only return agents with supervisor_routing.enabled=True
        category: Filter by category (e.g., "Validation", "Extraction")

    Returns:
        List of AgentDefinition objects
    """
    if not _initialized:
        load_agent_definitions()

    agents = list(_agent_registry.values())

    if enabled_only:
        agents = [a for a in agents if a.supervisor_routing.enabled]

    if category:
        agents = [a for a in agents if a.category == category]

    return agents


def get_supervisor_tools() -> List[Dict[str, Any]]:
    """
    Get tool metadata for all supervisor-enabled agents.

    Returns a list of tool definitions that can be used to build
    the supervisor's dynamic tool list.

    Returns:
        List of tool metadata dicts with keys:
        - tool_name: e.g., "ask_gene_specialist"
        - folder_name: The agent folder name (e.g., "gene")
        - description: From supervisor_routing.description
        - batchable: Whether agent handles batch requests
        - batching_instructions: How to format batch requests
        - agent_id: The agent's identifier
        - requires_document: Whether agent needs a loaded document
        - group_rules_enabled: Whether agent uses group-specific rules
    """
    if not _initialized:
        load_agent_definitions()

    tools = []
    for agent in _agent_registry.values():
        if not agent.supervisor_routing.enabled:
            continue

        tools.append({
            "tool_name": agent.tool_name,
            "folder_name": agent.folder_name,
            "description": agent.supervisor_routing.description,
            "batchable": agent.supervisor_routing.batchable,
            "batching_instructions": agent.supervisor_routing.batching_instructions,
            "agent_id": agent.agent_id,
            "requires_document": agent.requires_document,
            "group_rules_enabled": agent.group_rules_enabled,
        })

    return tools


def is_initialized() -> bool:
    """Check if agent definitions have been loaded."""
    return _initialized


def reset_cache() -> None:
    """Reset the agent cache (for testing)."""
    global _agent_registry, _agents_by_folder, _agents_by_package_and_id, _initialized
    _agent_registry = {}
    _agents_by_folder = {}
    _agents_by_package_and_id = {}
    _initialized = False
