"""Domain-pack metadata loading and registry helpers."""

from .loader import (
    DomainPackContractError,
    DomainFixturePackError,
    DomainPackMetadataError,
    load_domain_fixture_pack,
    load_domain_pack_metadata,
)
from .registry import (
    DomainPackDiscoveryFailure,
    DomainPackRegistry,
    DomainPackRegistryValidationError,
    LoadedDomainPack,
    load_domain_pack_registry,
)
from .validation_registry import (
    DomainPackValidationRegistry,
    FieldValidationPolicy,
    ValidationAttachmentOption,
    ValidationBindingState,
    ValidationRegistryError,
    ValidatorBinding,
    ValidatorBindingMatch,
    ValidatorMetadataEntry,
)
from .validation_supervisor import (
    ValidationSupervisorResult,
    append_validation_findings_to_envelope,
    run_validation_supervisor,
)
from .materialization import (
    project_evidence_anchor_projections,
    project_validation_summary_projections,
)
from .repair_patches import (
    DEFAULT_REPAIR_RETRY_BUDGET,
    REPAIR_CONTEXT_METADATA_KEY,
    DomainEnvelopeExtractorFinalClassification,
    DomainEnvelopeRepairPatch,
    DomainEnvelopeRepairRequest,
    RepairFinalClassification,
    RepairFinalStatus,
    RepairPatchOperation,
    RepairPatchResult,
    RepairPatchStatus,
    RepairRequestTarget,
    RepairRetryBudget,
    apply_repair_patch,
    build_repair_request,
    record_repair_final_classification,
    record_repair_request,
    record_validator_rerun_request,
)

__all__ = [
    "DomainFixturePackError",
    "DomainPackContractError",
    "DomainPackDiscoveryFailure",
    "DomainPackMetadataError",
    "DomainPackRegistry",
    "DomainPackRegistryValidationError",
    "DomainPackValidationRegistry",
    "FieldValidationPolicy",
    "LoadedDomainPack",
    "DEFAULT_REPAIR_RETRY_BUDGET",
    "REPAIR_CONTEXT_METADATA_KEY",
    "DomainEnvelopeExtractorFinalClassification",
    "DomainEnvelopeRepairPatch",
    "DomainEnvelopeRepairRequest",
    "RepairFinalClassification",
    "RepairFinalStatus",
    "RepairPatchOperation",
    "RepairPatchResult",
    "RepairPatchStatus",
    "RepairRequestTarget",
    "RepairRetryBudget",
    "ValidationAttachmentOption",
    "ValidationBindingState",
    "ValidationRegistryError",
    "ValidationSupervisorResult",
    "ValidatorBinding",
    "ValidatorBindingMatch",
    "ValidatorMetadataEntry",
    "append_validation_findings_to_envelope",
    "apply_repair_patch",
    "build_repair_request",
    "load_domain_fixture_pack",
    "load_domain_pack_metadata",
    "load_domain_pack_registry",
    "project_evidence_anchor_projections",
    "project_validation_summary_projections",
    "record_repair_final_classification",
    "record_repair_request",
    "record_validator_rerun_request",
    "run_validation_supervisor",
]
